runtime: nodejs10 # Tecnologia del servidor
service: default  # Nombre del servicio en appEngine
env_variables:    # Variables de entorno 
  NODE_ENV: production
beta_settings:
  cloud_sql_instances: myapinodejs:us-central1:prueba