openapi: 3.0.0
info:
  version: 1.0.0
  title: My Api NodeJS
  description: >-
    Esta API permite registrar y solicitar información de nuestros clientes
    actuales. 
  contact:
    name: Newton Angel Huamanñahui Robles
    url: https://github.com/angelhr28
    email: angelhuamannahui@gmail.com
  license:
    name: postgreSQL 12
    url: https://www.postgresql.org
paths: 
  
  /creacliente:
    post:
      description: Permite registrar los datos de un nuevo cliente interesado en la empresa.
      parameters:
        - name: creacliente
          in: query
          description: Registrar los datos de un nuevo cliente interesado en la empresa.
          schema:
            type: object
            properties:
              name_pers:
                type: string
                description: Nombre del cliente
                example: 'Angel'
              ape_pers:
                type: string
                description: Apellido del cliente
                example: 'Robles'
              edad_pers: 
                type: integer
                description: Edad del cliente
                example: 22
              fech_nac:
                type: string
                description: Fecha de nacimiento del cliente
                example: '28-04-1999'
      responses:
        200:
          description: Ejecucion correcta
          content:
            application/json:
              schema:
                type: object
                example: {
                  "status" : 200,
                  "msj": "Cliente registrado correctamente."
                }
        400:
          description: Errores controlados
          content:
            application/json:
              schema:
                type: object
                example: {
                  "status" : 400,
                  "msj"    : "Accion no permitida."
                }
        500:
          description: Errores desconocidos
          content:
            application/json:
              schema:
                type: object
                example: {
                  "status" : 500,
                  "msj"    : "Ocurrio un error."
                }
        
  /kpideclientes:
    get:
      description: Obtendremos el promedio de edades de los clientes registrados y sus respectiva desviacion standart para su evaluacion
      responses:
        200:
          description: Ejecucion correcta
          content:
            application/json:
              schema:
                type: object
                properties:
                  prom_edad:
                    type: integer
                    example: 25
                  desv_stand:
                    type: number
                    format: float
                    example: 22.5
        400:
          description: Errores controlados
          content:
            application/json:
              schema:
                type: object
                example: {
                  "status" : 400,
                  "msj"    : "Accion no permitida."
                }
        500:
          description: Errores desconocidos
          content:
            application/json:
              schema:
                type: object
                example: {
                  "status" : 500,
                  "msj"    : "Ocurrio un error."
                }
                       
  /listclientes:
    get:
      description: Lista a todos los clientes registrados dentro de la empresa, ademas de una fecha estimadad de su muerte respectiva
      responses:
        200:
          description: Ejecucion correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id_client:
                      type: integer
                      example: 1
                    name_client:
                      type: string
                      description: Nombre del cliente
                      example: 'Angel'
                    ape_client:
                      type: string
                      description: Apellido del cliente
                      example: 'Robles'
                    edad_client: 
                      type: integer
                      description: Edad del cliente
                      example: 22
                    fecha_naci:
                      type: string
                      description: Fecha de nacimiento del cliente
                      example: 'APRI 28 1999'
                    fecha_mortalidad:
                      type: string
                      description: Fecha de nacimiento del cliente
                      example: 'APRI 28 2080'
        400:
          description: Errores controlados
          content:
            application/json:
              schema:
                type: object
                example: {
                  "status" : 400,
                  "msj"    : "Accion no permitida."
                }
        500:
          description: Errores desconocidos
          content:
            application/json:
              schema:
                type: object
                example: {
                  "status" : 500,
                  "msj"    : "Ocurrio un error."
                }
servers:
  - description: My Server API 
    url: https://myapinodejs.uc.r.appspot.com